app/display/urls.py
from django.urls import path,include
from . import views

app_name = "display"

urlpatterns = [
    path('', views.index, name='display'),
    path('table/', views.index2, name="table-dev"),
    path('api/metrics/', views.MetricListAPI.as_view()),
    path('api/metrics/add', views.MetricCreateAPI.as_view()),
]

app/home/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

app/monitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('display/', include('display.urls')),
]

app/display/models.py
from django.db import models


class Metric(models.Model):
    temp = models.FloatField(
        verbose_name='Температура'
    )
    pressure = models.FloatField(
        verbose_name='Давление'
    )
    humidity = models.FloatField(
        verbose_name='Влажность'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время записили'
    )
    sensor = models.ForeighKey(
        to='Sensor',
        on_delete=models.CASCADE,
        verbose_name='Датчик',
        related_name='metrics'
    )

    def __str__(self):
        return f'Изменерения от {self.dateandtime.date()} по времени {self.dateandtime.time()} UTC'


class Location(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=256,
        blank=True,
        null=True,
    )
    parent = models.ForeighKey(
        to=self,
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return self.name


class Sensor(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=256,
        blank=True,
        null=True,
    )
    serial = models.CharField(
        verbose_name='Серийный номер',
        max_length=256,
    )
    specifications = models.JsonField(
        verbose_name='Характеристики'
    )
    location = models.ForeighKey(
        to='Location',
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.name or self.serial

app/home/models.py
from django.db import models

# Create your models here.

app/display/views.py
from django.shortcuts import render
from display.models import Metric
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.gererics import ListAPIView, CreateAPIView
from rest_framework.authentication import SessionAuthentication

from display.serializers import MetricSerializer


def index(request):
    allvariables = Metric.objects.order_by('-id')[:10]
    return render(request, "display/out.html", {"all": allvariables})


def index2(request):
    allvariables = Metric.objects.order_by('-id')[:10]
    return render(request, "display/outtable.html", {"all": allvariables})


# class DataView(APIView):
#     def get(self, request):
#         articles = Data.objects.all()
#         serializer = DataSerializer(articles, many=True)
#         return Response({"datas": serializer.data})
#
#     def post(self, request):
#         data = request.data.get('data')
#         serializer = DataSerializer(data=data)
#         if serializer.is_valid(raise_exception=True):
#             data_saved = serializer.save()
#         return Response({"success": "Article '{}' created successfully".format(data_saved.dateandtime)})


class MetricListAPI(ListAPIView):
    serializer_class = MetricSerializer
    authentication_classes = [SessionAuthentication]

    def get_queryset(self):
        return Metric.objects.all()


class MetricCreateAPI(CreateAPIView):
    serializer_class = MetricSerializer
    authentication_classes = [SessionAuthentication]

    def get_queryset(self):
        return Metric.objects.all()

app/home/views.py
from django.shortcuts import render


def index(request):
    return render(request, "home/homepage.html")

app/display/templates/display/out.html
{% extends "home/homepage.html" %}
{% block head %}
	<meta charset="utf-8">
	<title>django-google-charts</title>
	<link rel="stylesheet media="all">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        setTimeout(F1, 2000);
            function F1(){
                $.get('/display/table', function(data){
                    $('tbody').html(data);
                });
                setTimeout(F1, 2000);
            }
        </script>
{% endblock %}
{% block charts %}
<div class="container-fluid">
<table class="table table-sm table-light">
  <thead>
    <tr>
      <th scope="col">Температура</th>
      <th scope="col">Давление</th>
      <th scope="col">Влажность</th>
      <th scope="col">Время измерения</th>
    </tr>
  </thead>
  <tbody  id="datas">

  </tbody>
</table>
</div>
{% endblock %}

app/display/templates/display/outtable.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <title>table</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
<div class="container-fluid">
<table class="table table-light" style="background-color:#e3f2fd;">
  <tbody  id="datas">
  	{% for data in all %}
    <tr>
		<td>{{ data.temp }}</td>
      	<td>{{ data.pressure }}</td>
      	<td>{{ data.humidity }}</td>
		<td>{{ data.dateandtime }}</td>
    </tr>
  	{% endfor %}
  </tbody>
</table>
</div>
</body>
</html>

app/home/templates/home/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <title>СУПЕРМОНИТОР</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        {% block head %}
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:#e3f2fd;">
  <a class="navbar-brand" href="#">BilMon</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'display:display' %}">Table</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'display:table-dev' %}">Table-Dev</a>
      </li>
    </ul>
  </div>
</nav>
        <div class="container" style="background-color:#fffff1">
            <h1 class="text-center">суперпупер система мониторинга</h1>
        </div>
    {% block charts %}
    {% endblock %}
    </body>
</html>